### ISSUE TITLE
Someone please help, it just wont run.

### ISSUE THREAD

**Issue by xfuzz** [clough42/electronic-leadscrew#121]
Please help me figure this out
I have it all together assembled for testing. Servo wont spin. It gets energized so I can't turn by hand when powered. All the led's light up on the TI and boost boards.  The control pannel lights up.when I spin the omron encoder the rpm's  show up on the control panel. The buttons show changes with each push ,  but servo does not spin. I have triple checked continuity all good. I am perty sure all dip switches are set correct as well. I tried going to the older version software 9.1 to up load the els software too. One thing when doing so is I do not get the red  pause break point icon on the TI  software like Jame's does in his videos. It just seems to complete to upload without stopping no break with red icon. The servo & encoder are from Automation Tech. The number on the encoder is different it is ES-D508 , servo is ES- M32320S. I called as when I received them,  I ordered same as the ones James used. They told me they are exactly the same and numbered for a different market. I am lost. One  more thing,  I purchased my Launchpad  directly from TI , it did not have the tape  on the dip switches like James video. Not sure what that means.  **_I have uploaded pictures of the wiring below_**

**Comment by mac651955** [comment]
Mine didn’t work when I initially set it up.  Flip the switches on the micro processor back and forth a couple times to make sure they make contact.  Additionally go ahead and make all your connectors up and use them as your problem may be in connections.

**Comment by xfuzz** [comment]
Thanks for 5hevinout. I tried the switch flipping multiple times M I red all the post and someone suggested it prior to you. I have continuity on all of the connections. The servo is getting power as I stated if I flip one of the two dip switches on the servo encoder it will rotate back and forth one revolution non stop. It's  something simple , but what?

**Comment by mac651955** [comment]
Are you using the servo encoder combo that James used or something different.  If it is the same double check your three leads from the servo to the servo controller.  Make sure they are correctly connected U, V, W. You might be getting your phases working against each other.

**Comment by xfuzz** [comment]
Yes. As I indicated above  according to Automation tech it isi identical. . I will have to find the schematic,  I have have brown on "U", blue on "V", black on " W", I think that is correct.

**Comment by xfuzz** [comment]
![20201209_151957](https://user-images.githubusercontent.com/34842936/105942251-dc8d3000-602c-11eb-8ff0-aea909bd46f9.jpg)

**Comment by xfuzz** [comment]
![20210126_191856](https://user-images.githubusercontent.com/34842936/105942278-e6af2e80-602c-11eb-8a3e-8bd45d245db9.jpg)
![20210126_192014](https://user-images.githubusercontent.com/34842936/105942281-e878f200-602c-11eb-894d-8d008e6a0ddd.jpg)
![20210126_192056](https://user-images.githubusercontent.com/34842936/105942284-ea42b580-602c-11eb-92b0-8701cb7e0601.jpg)
![20210126_192146](https://user-images.githubusercontent.com/34842936/105942292-edd63c80-602c-11eb-9012-850ec4e5fe5c.jpg)
![53018004_10219423981133860_4789615904931446784_n](https://user-images.githubusercontent.com/34842936/105942295-ef076980-602c-11eb-8a08-2b3ef09d2b2f.jpg)

**Comment by JonWoellhaf** [comment]
Do you have the Pro_Tuner, hardware, and software manuals for your ES-D508?

If not, you can download them from https://mecheltron.com/en/product/es-d508.

I think you will need all three manuals.

Do you have an oscilloscope?

Your connections from James' Boost Board to the ES-D508 should be as shown at the top of page 8 of the hardware manual. The boost board has a "sinking" type output.

Do you have a jumper from pin 1 of the driver connector to pins 3 and 5 of that connector? In the photo, it looks like you do, but I want to be sure.

**Comment by candera** [comment]
I'm actually having a similar problem (see #125), and am no expert, so take the following for what it's worth, which is "not much". 

I took a long look at the pictures you posted, and I can't see anything wrong. You've checked continuity, and it sounds like when you flip DIP switch #2 it runs the self test, which seems to indicate that the motor is running. The only things I can think of are either that continuity is not actually good or that there's a lot of noise in the system. But with noise you'd expect some movement, even if random.

The critical pin for you is the STP- pin. If ENA- were not pulled low, the motor wouldn't be energized. And DIR- doesn't really matter - whether it's high or low the motor is still going to turn, it's just which direction. Unfortunately it's a little hard to test, since in order to turn the motor it needs to go high and low a bunch of times. I did try wiring a pushbutton switch between ground on the TI board and the STP- pin so that I could press it a bunch of times and generate a pulse train. I even tied the ENA- and DIR- pins low to try to take out any variables. I *think* that was a good test (maybe someone else can tell me why it's a bad idea) so perhaps you could replicate it. If pushing the button doesn't rotate the motor at all then perhaps it is a motor controller problem. Iit might take a lot of pushes, since if you're configured for, say, 800 microsteps per revolution, each push is only going to move it like a third of a degree.

In my case, I believe perhaps the motor is bad, as I can get at best random movement from it. I've ordered a stepper to replace it. Hopefully I'll have more luck with that. The hybrid servo concept is very cool, though - I really wanted it to work, so I sort of hope it's just a bad motor rather than some weird thing with my setup.

**Comment by xfuzz** [comment]
Jon et me start with a huge thank you for your assistance i downloaded the manuals. Not sure what I am looking at. I do not have an oscilloscope.Yes all the positives are connected via a jumper wire from one to the other two. Continuity on all, I do not have the required cable to enter data to the encoder. I will order one right away if that is what I need.  Actually I don't know a sinking output from one  that is not. I can follow instructions though.

**Comment by mac651955** [comment]
In the photos it appears that (if you used the same wire colors as the encoder) your encoder is wired wrong.  The first pin from the bottom is 0v common and you have what appears to be the blue wire going to it.  Also you have 6 connections on your plug and that is a five pin header.  Check your wiring then maybe try a five pin connectors.

**Comment by xfuzz** [comment]
Mac I triple checked and blue is marked common the omron. i up loaded pic. the 6 spot on the connector is  empty

**Comment by JonWoellhaf** [comment]
xfuzz,

OK, let's see if I can help you get this working. Troubleshooting would be much easier if you had an oscilloscope. Can you borrow one?

Candera (above) offered some good information. I'd like to simplify the problem as much as possible.

First though, I think it's important you understand the schematic at the top of page 8 in the driver's hardware manual. Do you?

**Comment by xfuzz** [comment]
![dip](https://user-images.githubusercontent.com/34842936/106032880-0b43ee80-609f-11eb-88ec-418af7c4bd08.jpg)
![encoder wire](https://user-images.githubusercontent.com/34842936/106032891-0d0db200-609f-11eb-9d45-5d9e262e948e.jpg)
![omron](https://user-images.githubusercontent.com/34842936/106032896-10a13900-609f-11eb-9e06-48d040a0ea9b.jpg)
![wire](https://user-images.githubusercontent.com/34842936/106032905-13039300-609f-11eb-89ab-01a9164136f4.jpg)

**Comment by xfuzz** [comment]
I would not how how to use one ,  have no one to borrow from. I uploaded more pics of the wiring I think I do understand page 8.

**Comment by mac651955** [comment]
Did your server come with the signal cable, if it did are you using it.  Just covering all bases.

**Comment by xfuzz** [comment]
Mac yes it did I am using it

**Comment by xfuzz** [comment]
![wire to ti](https://user-images.githubusercontent.com/34842936/106034328-c9b44300-60a0-11eb-97d7-a85f71b233ff.jpg)

**Comment by JonWoellhaf** [comment]
OK.
I am confused by the statement at the top of page 8. It reads, "For the enable signal, apply 0V between ENA+ and ENA- or leave them unconnected to enable the drive." If left unconnected, the LED in the drive's opto isolator will be off. I would expect that to be interpreted as disabled, but the text says off is enabled. I expect the sense of this input can be changed in the software.

So please try this:
1) Power off.
2) Disconnect the ENA- wire from pin 6 of the driver. Tape its end or attach a wire nut so it doesn't short against something.
3) Power on. Does the control panel operate normally? When you spin the encoder do you see RPM displayed? Does the motor turn?

**Comment by candera** [comment]
That is pretty weird: definitely seems like powering the LED should enable the drive. It should be easy to tell whether enable is active high or low, though, because when not enabled the shaft should spin pretty freely. Again, wiring ENA+ to 5V and ENA- to ground should be a good way to verify. 

If it turns out the logic is inverted (and perhaps it's that way to allow the motor to be enabled without requiring the input to be driven) then it may be simply that you need to change Configuration.h to set `#define INVERT_ENABLE_PIN true`, or to `false` if it's already true. See [this line](https://github.com/clough42/electronic-leadscrew/blob/master/els-f280049c/Configuration.h#L78).

It's easy to tell whether you're driving the DIR and ENA inputs pins high or low, BTW. Just use an multimeter and check the DC voltage across the two pins (say, ENA- and ENA+). If you're driving ENA- low, you'll see about 5V across them. I would think that means "motor is enabled" but again that wording in the manual suggests otherwise.

**Comment by xfuzz** [comment]
Jon, ok did that .the rpm shows on display when I spin by hand the omron.

**Comment by xfuzz** [comment]
candra I get 5.3 volts between ena+ and ena

**Comment by JonWoellhaf** [comment]
As Craig said, with ENA- disconnected, can you turn the motor by hand?

**Comment by xfuzz** [comment]
jon, not easy i get a resistance like it is fighting me but can not complete a half turn

**Comment by JonWoellhaf** [comment]
OK. That indicates the drive is enabled with the opto isolator off. As Craig said, you will need to change INVERT_ENABLE_PIN true in James' software. Or, after you get the RS-232 cable and run ProTuner, make the change there.

New thought. I remember others having a problem because they connected the encoder cable directly to the ES-D508 WITHOUT using the supplied extension cable. Take a look at page 11 in the manual. It clearly shows the extension cable being used and says "* must be used." I think it's more than just an extension cable, and also makes some wiring changes. Are you using the extension cable?

**Comment by candera** [comment]
One other check you could do: connect the motor control wires up to the TI board again, power everything up and give the encoder a spin. That should force the board to enable the motor. Measure the voltage across ENA+ and ENA-. It should NOT read 5V. If it does, that means you need to invert the enable pin in the firmware, recompile and flash it onto the board. 

If you hit the power button on the control panel, it should disable the motor. So while you're measuring voltage, you can see if it flips from 0 to 5V and back again when you toggle the power button on the control panel. Just as one more verification.

**Comment by candera** [comment]
But of course if the voltage is 5V when the motor should be DISABLED, then your firmware setting is already correct and we'll have to look elsewhere for the problem.

**Comment by xfuzz** [comment]
Jon yes I musing the iextention cable. I looking at james software to see what it say now

**Comment by xfuzz** [comment]
this is what it says in config h
#define INVERT_ENABLE_PIN true
#define INVERT_ALARM_PIN true

**Comment by candera** [comment]
Which is probably correct, at least as far as the enable pin goes. You can verify it as described above if you want to make sure.

**Comment by xfuzz** [comment]
now i am getting different reading o volts. around .158 volts

**Comment by xfuzz** [comment]
think i should try to flash the software again?

**Comment by JonWoellhaf** [comment]
Yes! It certainly could be incorrect TI board switch settings. As others have said, the switches are a bit flakey and may appear to be in the correct position but not actually making contact internally. Some advise to move the switch back and forth several times.

You said your board did NOT have tape over the switches. I am very surprised to hear that. I wonder if you got a used, and possibly defective board, but can't imagine TI doing that intentionally.

**Comment by xfuzz** [comment]
I know it seemed strange to me that there was no tape on the dips .Especially after James made so much mention of how hard they were to remove. I could order another one at this point I am chasing dollars anyway. So do you think  I need that programing cable and should I order a new TI board? I upgraded a pic of the placement of the dips as I have them positioned.

**Comment by JonWoellhaf** [comment]
If you intend to keep your ES-D508, I think you will need the RS-232 programming cable and the free ProTuner software.
With the Enable input disconnected, does spinning the encoder -- like with a drill -- cause the motor to turn?

**Comment by xfuzz** [comment]
i tried using a drill to spin it with no result. I just re-flashed and now the rpms do not shown on the display.

**Comment by xfuzz** [comment]
the only thing i did was flip the dips back nd forth a few times and re flashed
 now no reading of rpm ondisplay

**Comment by JonWoellhaf** [comment]
OK. No RPM display. Do the control panel buttons work normally?

**Comment by xfuzz** [comment]
yes

**Comment by xfuzz** [comment]
Jon are you in the USA

**Comment by JonWoellhaf** [comment]
OK. Double check the encoder wiring and see if something broke loose. I'm in Utah.

**Comment by candera** [comment]
I'm trying to remember if my dips had tape on them. I think they did not - perhaps TI made a change where they aren't taping them any more. One of my mistakes was not flipping the switches to the correct position. For me that manifested as the control panel not working, since S9 enables GPIO32/33, which are connected to CLK and STB on the control panel. The other switches affect only the encoder header, but since you're no longer seeing RPM it sounds like maybe they are no longer set correctly. 

Check them vs: 

```
S3.1 = 0 Connects eQEP1 to J12
S3.2 = 0 Connects eQEP2 to J13
S4 = 1 Connects eQEP1 to J12
S9 = 1 (default) -- Connects GPIO32/33 to BoosterPack site 2 pins
S6 and S8 can be in any position. 0 is the default.
```

**Comment by candera** [comment]
It's not surprising that you would see readings like 0.1V, BTW. When those pins aren't being driven to ground they float. There's probably some very high resistance path to ground through them at that point, which would divide the 5V signal between the internal resistor and wind up with a 5V to 4.9V (relative to ground) reading across the two pins. Or something like that. I certainly saw low non-zero readings when I was doing the same test.

**Comment by xfuzz** [comment]
nope they are all good

**Comment by xfuzz** [comment]
the dip switch have dot on one end and a double zero symbol at the other which is on

**Comment by xfuzz** [comment]
ok got the rpm to show again but no servo movement

**Comment by xfuzz** [comment]
OK wold anyone be up for me sending the whole set up. I pay for shipping both ways of course plus your time and any parts if needed?

**Comment by xfuzz** [comment]
you could try my boards on your set up see if they work.

**Comment by JonWoellhaf** [comment]
Are you on Practical Machinist?

**Comment by xfuzz** [comment]
The only thing I changed in the software is I have a 8tpi leedscrew

**Comment by xfuzz** [comment]
Jon do you mean do I subscribe to the forum?I get theri emails but have not paid for membership yet

**Comment by JonWoellhaf** [comment]
There is no fee to join Practical Machinist at <https://www.practicalmachinist.com/>. I am known there as Yan Wo. If you join you can send me a private message and I can respond with my address. I don't want to send it in the clear. I'll be happy to look at your setup. Where are you located?

**Comment by xfuzz** [comment]
Roseville Michigan just outside of Detroit

**Comment by JonWoellhaf** [comment]
OK, a little too for of a drive. :)

**Comment by candera** [comment]
You're a good guy Jon. Good luck xfuzz! For my part I'm hoping a new motor does it for me. If not I imagine I will be mentioning my woes. :)

**Comment by xfuzz** [comment]
Just a tad.  Ok I signed up. My user is Xfuzz

**Comment by xfuzz** [comment]
Craig, your a good guy as well. I truly appreciate the huge block f time  you gave me thank you ever so much and good luck

**Comment by xfuzz** [comment]
Jon how do I find you on PM the search for Yan Wo bring up a lot f Chinese writting

**Comment by JonWoellhaf** [comment]
Thanks, guys.

Let's try a little more remote troubleshooting before you send anything.

Do you have any resistors in the range 1000 to 10,000 ohms?

I sent you a private message. When you log into Practical Machinist, Right at the top to the right you'll see NOTIFICATIONS. There should be a dot there indicating you have a PM (private message). Click it and you should see my message to you.

You should be able to find me as Yan Wo by clicking Search and Search Forum Discussions. That'll bring up a form where you can type my user name with Exact name checked. When you click Search Now, you'll see my user name underlined. Click it and you'll see my profile, and under that Send Private Message.

**Comment by xfuzz** [comment]
OK, No resisters I never do any electronics I built several computers but that was mostly assembling parts  .

**Comment by xfuzz** [comment]
Yes I have your message now.

**Comment by JonWoellhaf** [comment]
OK. PM your address and I'll send a couple resistors so we can do some troubleshooting.

**Comment by xfuzz** [comment]
ok

**Comment by JonWoellhaf** [comment]
When you flip SW2 to ON, does the motor alternately turn 1 revolution CW then 1 revolution CCW continuously?

**Comment by xfuzz** [comment]
When I flip s2 on the esd508 to the down position the servo rotates back and fort one reveloution at a time non stop.

**Comment by JonWoellhaf** [comment]
OK. Please try this, if you want:
1) Power off.
2) Remove all the wires from the Control Signal connector except those on pin 1. Cap or tape the wires you removed.
3) Connect a wire to pin 2.
4) Connect a wire to one of the pins labeled GND on the TI board. Be sure not to short a GND pin to an adjacent pin.
5) Power on.
6) Repeatedly short together the wire from pin 2 to the wire from GND. Do this a LOT.
Does the motor move at all?

**Comment by xfuzz** [comment]
give me a moment I gotta set it up

**Comment by xfuzz** [comment]
what is the control  signal? the servo encoder?

**Comment by JonWoellhaf** [comment]
The GND is on the TI board.

**Comment by JonWoellhaf** [comment]
I have to sign off for a few hours. We can work on this some more tomorrow. Ideas, anyone?

**Comment by xfuzz** [comment]
which ground on ti board , anyone?

**Comment by xfuzz** [comment]
Ok talk tomorrow

**Comment by xfuzz** [comment]
Jon, OK,I tried the connecting the wire to pin 1 ans using a wire on pin 2 touching a ground pin on TI board multi times very fast. Nothing moved. I picked up 2 1000ohm resistors 2% the guy said that is what i needed.

**Comment by JonWoellhaf** [comment]
OK. No motor movement when repeatedly shorting pin 2 to ground with pin 1 at 5 volts. Unfortunately, I'm not able to test this myself, so I may be missing something. At this point, it seems the driver may be defective.

Candera: Are you able to try that experiment?

Xfuzz: I sent you a couple resistors and a jumper wire.

New thought: The green connector that plugs into J2 on James' Boost board is a bit tricky to use. Please see his explanation at about 16:45 on his Part 20 video at <https://www.youtube.com/watch?v=84O8iWemqxY&list=PLDlWKv7KIIr90ZZ7Zqt-ge5nVVdS3WVgg&index=21>. Please verify your wires are attached correctly. And check the connectors on the driver, too. They may have a similar gotcha.

Next test: Since you have some resistors, please try this:
1) Power off.
2) Remove all the wires from the J2 connector on the boost board.
3) Connect a resistor between + and STP- on the connector.
4) Set your meter to AC volts and clip one meter lead to the wire going into + and the other to the lead going into STP-. Doesn't matter which is which. Be sure the meter leads don't touch each other or anything on the boards.
5) Power on. You should see a couple millivolts (from noise) on the meter.
6) Spin the encoder. You should see 50 or 60 millivolts when spinning the encoder. Note: This may be dependent on the meter you're using. I believe James thought this was a good idea until he tried it and saw no change. I have no explanation for that.

**Comment by xfuzz** [comment]
ok going t try

**Comment by candera** [comment]
Yeah, I tried that. Pulled enable and direction lines to ground, then wired ground to PUL- via a switch. Clicked it a ton of times. No movement.

One thing I noticed is that the driver I got differs from the one in the picture on the eBay listing. So I'm sort of wondering if they ran out of stock of the thing I ordered, grabbed a return off the shelf and ditched it on me. :p

My new motor arrived this morning. Driver arrives later today. That at least should tell me whether it's the motor or something else. My power supply is kind of suspect, too, so we'll see.

**Comment by xfuzz** [comment]
here is how I set it up
![20210128_150518](https://user-images.githubusercontent.com/34842936/106193668-d2c61280-617b-11eb-8008-33493112e48c.jpg)

**Comment by xfuzz** [comment]
meter
![20210128_152153](https://user-images.githubusercontent.com/34842936/106194392-c42c2b00-617c-11eb-8ef6-b831001c0833.jpg)

**Comment by xfuzz** [comment]
ok i am using my drill to spin omron. spinning at 1000rpm i get 77.2 no spin i get52 to 56.on meter

**Comment by xfuzz** [comment]
changed setting on meter it now reads no spin 61.2-68.4. spinning at 1ooorpm it reads 99.8-100.4mv

**Comment by JonWoellhaf** [comment]
I don't see my latest comment. I wonder if it got lost in the aether. I wrote:

OK. It looks to me that your TI board is working. If it wasn't pulsing you'd see no change in voltage.

I think either the driver, motor, or encoder is defective. Sorry. Can you get a replacement?

If you want to send me just the TI board, boost board, and control panel, I'll check them out.

**Comment by xfuzz** [comment]
OK. ill pack them up and send those items. Thanks.

**Comment by xfuzz** [comment]
I doubt it is the omron as it sends rpms to the control panel. the control panel seems ok as well as it displays all button pushes and rpm. logic implys the TI, or servo encoder and servo itself. Thoughts?

**Comment by JonWoellhaf** [comment]
I meant the encoder on the servo motor. I think your spindle encoder is fine.

**Comment by xfuzz** [comment]
ok just so I am clear,send the servo encoder{ES-D508) the TI and boost board?

**Comment by JonWoellhaf** [comment]
Just the TI board, the boost board, and your control panel.

**Comment by xfuzz** [comment]
Got it

**Comment by JonWoellhaf** [comment]
Don't send the ES-D508, motor, or power supply.

**Comment by JonWoellhaf** [comment]
Did you try it with enable and direction open?

**Comment by candera** [comment]
So, good news. My new motor arrived today, and when I wired it up it seemed
to work perfectly right out of the gate. I got a stepper instead of a servo
so I might try again, but looks like I just got a bum motor!

**Comment by xfuzz** [comment]
Jon, I mailed it this morning. I enclosed a return pre paid label. use it for the return trip home. thanks

**Comment by JonWoellhaf** [comment]
OK. I’ll let you know as soon as it arrives.

**Comment by xfuzz** [comment]
It seems the package is on a sight seeing trip. It was sent 2 day priority,  gotta love the USPS
February 1, 2021, 4:11 pm
Departed USPS Regional Facility
SOUTHERN ME DISTRIBUTION CENTER 
Your item departed our USPS facility in SOUTHERN ME DISTRIBUTION CENTER on February 1, 2021 at 4:11 pm. The item is currently in transit to the destination.
January 31, 2021, 12:53 am
Arrived at USPS Regional Facility
SOUTHERN ME DISTRIBUTION CENTER 
January 30, 2021
In Transit to Next Facility
January 29, 2021, 5:11 pm
Arrived at USPS Regional Origin Facility
DETROIT MI NETWORK DISTRIBUTION CENTER 
January 29, 2021, 11:03 am
USPS in possession of item
ROSEVILLE, MI 48066 
January 28, 2021
Pre-Shipment Info Sent to USPS, USPS Awaiting Item

**Comment by xfuzz** [comment]
FINALLY! USpS says it was delivered. So glad I sent it Priority.  Let me know what you think.

**Comment by JonWoellhaf** [comment]
I think a guy reenacting the Mormon immigration put it in his handcart and walked it across the plains!

Looking at it now.

**Comment by JonWoellhaf** [comment]
SOLVED! (I think). Check your private messages on Practical Machinist.

**Comment by candera** [comment]
I'm curious. What was it?

**Comment by xfuzz** [comment]
A unsoldered pin. Jon discovered it and fixed it. Runs perfict now.

**Comment by candera** [comment]
Awesome, glad you got it working. I've been chipping away at the other hard problem: how to attach everything to the lathe!

**Comment by xfuzz** [comment]
Do you have access to a 3d printer?. Check thinigieverse.com there are
several stl files of mounts and gears search clough42 and els to find the
files.

**Comment by candera** [comment]
I do have a 3D printer, and I've already printed a bunch of pulleys. I even printed a belt in flexible filament. So I'm not stuck or anything: just working my way through the process. :)
